export const GET_CITIES = "GET_CITIES";
export const ADD_CITY = "ADD_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const UPDATE_CITY = "UPDATE_CITY";
export const CITIES_LOADING = "CITIES_LOADING";
export const SET_ERROR = "SET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const GET_CITY = "GET_CITY";

export const GET_ITINERARIES = "GET_ITINERARIES";
export const GET_ITINERARY = "GET_ITINERARY";
export const UPDATE_ITINERARY = "UPDATE_ITINERARY";
export const DELETE_ITINERARY = "DELETE_ITINERARY";
export const CREATE_ITINERARY = "CREATE_ITINERARY";
