export const GET_CITIES = "GET_CITIES";
export const ADD_CITY = "ADD_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const UPDATE_CITY = "UPDATE_CITY";
export const CITIES_LOADING = "CITIES_LOADING";
export const SET_ERROR = "SET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const GET_CITY = "GET_CITY";

export const GET_ITINERARIES = "GET_ITINERARIES";
export const FETCH_ITINERARIES_FAILED = "FETCH_ITINERARIES_FAILED";
export const GET_ITINERARY = "GET_ITINERARY";
export const UPDATE_ITINERARY = "UPDATE_ITINERARY";
export const DELETE_ITINERARY = "DELETE_ITINERARY";
export const CREATE_ITINERARY = "CREATE_ITINERARY";
export const GET_ITINERARIES_BY_CITYNAME = "GET_ITINERARIES_BY_CITYNAME";
export const GET_ITINERARIES_BY_USER = "GET_ITINERARIES_BY_USER";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
